INSERT INTO courseProvider (providerName) VALUES ('NTNU');
INSERT INTO courseProvider (providerName) VALUES ('Oracle');
INSERT INTO courseProvider (providerName) VALUES ('Apache Software Foundation');
INSERT INTO courseProvider (providerName) VALUES ('Pearson');
INSERT INTO courseProvider (providerName) VALUES ('Microsoft');
INSERT INTO courseProvider (providerName) VALUES ('Amazon');
INSERT INTO courseProvider (providerName) VALUES ('Adobe');
INSERT INTO courseProvider (providerName) VALUES ('Google');
INSERT INTO courseProvider (providerName) VALUES ('Apple');
INSERT INTO courseProvider (providerName) VALUES ('Handelshøyskolen BI');
INSERT INTO courseProvider (providerName) VALUES ('University of Oslo');
INSERT INTO courseProvider (providerName) VALUES ('University of Bergen');
